### ISSUE TITLE
Undefined index: isUpvoted

### ISSUE THREAD

**Issue by VanillaScent** [ReFlar/gamification#18]
Hello, I receive the error seen in the title whenever me or someone else would edit their or someones comment.

```
POST https://www.localhost/api/posts/100

<br />
<b>Notice</b>:  Undefined index: isUpvoted in <b>/var/www/site/public_html/vendor/reflar/gamification/src/Listeners/SaveVotesToDatabase.php</b> on line <b>80</b><br />
<br />
<b>Notice</b>:  Undefined index: isDownvoted in <b>/var/www/site/public_html/vendor/reflar/gamification/src/Listeners/SaveVotesToDatabase.php</b> on line <b>84</b><br />
<br />
<b>Fatal error</b>:  Uncaught exception 'RuntimeException' with message 'Output has been emitted previously; cannot emit response' in /var/www/site/public_html/vendor/zendframework/zend-diactoros/src/Response/SapiEmitterTrait.php:31
Stack trace:
#0 /var/www/site/public_html/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php(27): Zend\Diactoros\Response\SapiEmitter-&gt;assertNoPreviousOutput()
#1 /var/www/site/public_html/vendor/zendframework/zend-diactoros/src/Server.php(162): Zend\Diactoros\Response\SapiEmitter-&gt;emit(Object(Flarum\Api\JsonApiResponse))
#2 /var/www/site/public_html/vendor/flarum/core/src/Http/AbstractServer.php(36): Zend\Diactoros\Server-&gt;listen(Object(Zend\Stratigility\NoopFinalHandler))
#3 /var/www/site/public_html/api.php(16): Flarum\Http\AbstractServer-&gt;listen()
#4 {main}
  thrown in <b>/var/www/site/public_html/vendor/zendframework/zend-diactoros/src/Response/SapiEmitterTrait.php</b> on line <b>31</b><br />
```

if I reload the page after it says an known error occured, it is edited.
Ofcourse it shouldn't be like this.

Any way to fix this on my side or will this be fixed in an update?

**Comment by gwillem** [comment]
Same on FreeFlarum, it's the most common error message.

**Comment by Ralkage** [comment]
@VanillaScent @gwillem this will be fixed in a patched update!
